In [ ]:
#2.4 copies and views
#2018-04-02

In [6]:
#2.4.1 no copy at all
import numpy as np
a = np.arange(12)
print("a(1):",a)
b = a #没有创建新的对象，a、b是相同array对象的两个名字
print(b is a) #a和b指向同一个数组对象，对a和b的修改操作同一个数组对象
print("a.shape:",a.shape,"b.shape:",b.shape)
b.shape = 3,4 #使用b进行修改shape，则a的shape也会改变
print(a.shape)

print("---------------------")
#python传递可变对象作为引用，所以函数调用不会复制
def f(x):
    print(id(a)) # id 是一个对象独一无二的标识，通过id()来获取

print(id(a))
print(f(a)) #可变对象作为引用传递

a(1): [ 0  1  2  3  4  5  6  7  8  9 10 11]
True
a.shape: (12,) b.shape: (12,)
(3, 4)
---------------------
97729232
97729232
None


In [26]:
#2.4.2 view or shallow copy
#浅拷贝
import numpy as np
#不同的数组对象共享相同的数据，
# view()方法创建一个新的数组对象，但是看到相同的数据
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(a)
b = a.view() #创建一个新的数组对象，但是和a拥有相同的数据
print("view():",b is a) #a b是两个不同的对象
print("b.base与a:",b.base is a)
print("b.base:",b.base) #显示b的数组数据,只有在view()创建出的对象有base
print("a.base:",a.base) #返回None
# 查看view()创建出的对象不拥有自己的数据，数据有a拥有
print("b.flags.owndata:",b.flags.owndata)
b.shape = 2,6 #不会修改a的shape,只是b的shape会改变
print("a.shape: ",a.shape,"b.shape:",b.shape)
print("a:",a)
print("b:",b)
#虽然不能更改shape，但是可以修改底层的数据，例如
b[0,4] = 1024 #可以修改底层数据
print("modfied, a:\n",a)
print("modifed, b:\n",b)
s = a[:,1:3] #切片，s指向a的某一部分
print("s:\n",s)
s[:] = 10 #将s指向的部分全部赋值为10
print("modifed,s:\n",s)
print("mofified,a:\n",a)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
view(): False
b.base与a: True
b.base: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a.base: None
b.flags.owndata: False
a.shape:  (3, 4) b.shape: (2, 6)
a: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
modfied, a:
 [[   0    1    2    3]
 [1024    5    6    7]
 [   8    9   10   11]]
modifed, b:
 [[   0    1    2    3 1024    5]
 [   6    7    8    9   10   11]]
s:
 [[ 1  2]
 [ 5  6]
 [ 9 10]]
modifed,s:
 [[10 10]
 [10 10]
 [10 10]]
mofified,a:
 [[   0   10   10    3]
 [1024   10   10    7]
 [   8   10   10   11]]


In [29]:
#2.4.3 deep copy
#深拷贝
import numpy as np
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print("create a:\n",a)
d = a.copy() #copy()方法直接拷贝完全的数组，包括数据
#a和d的id是不同的
print("id ,a:\n",id(a))
print("id ,d:\n",id(d))
print("copy b:\n",d)
print("a和d是完全不同的：",d is a)
print("d的底层数据不和a共用：",d.base is a)
print("a.base :",a.base) #只有copy()出来的对象才有base
#d、a的修改不会相互干扰，因为两者是完完全全的两个数组
#a和d不共享任何东西
d[0,0] = 9999
a[0,0] = 2222
print("modified,d:\n",d)
print("modified,a:\n",a)






create a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
id ,a:
 85386544
id ,d:
 85388224
copy b:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a和d是完全不同的： False
d的底层数据不和a共用： False
a.base : None
modified,d:
 [[9999    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]
modified,a:
 [[2222    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]


In [59]:
#2.4.2 functions and methods overview
#有用的函数和方法
import numpy as np
#（1）Array Creation
#arange、array、copy、empty、empty_like、eye、fromfile、
# fromfunction、identity、linspace、logspace、mgrid、ogrid、
# ones、ones_like、r、zeros、zeros_like
a = np.zeros_like([1,2,3,7,8])
print("zeros_like:\n",a)
a = np.ones_like([1,2,3,7,8])
print("zeros_like:\n",a)
a = np.zeros([3,4])
print("zeros:\n",a)
#（2）Conversions
#ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat

#（3）Manipulations
#array_split, column_stack, concatenate, diagonal, dsplit, 
# dstack, hsplit, hstack,ndarray.item, newaxis, ravel, repeat, 
# reshape, resize, squeeze, swapaxes, take,transpose, vsplit, vstack

#（4）Questions
#all, any, nonzero, where
a = np.array([1,2,3,0,5,6,7,8])
b = np.all(a)
print("all:\n",b)
#（5）Ordering
#argmax, argmin, argsort, max, min, ptp, searchsorted, sort

#（6）Operations
#choose, compress, cumprod, cumsum, inner, ndarray.fill, 
# imag, prod, put, putmask, real,sum

#（7）Basic Statistics
#cov, mean, std, var
a = np.array([[6,2],[7,8],[4,5]])
b = np.array([[1,0],[3,4]])
c = np.array([6,2])
d = np.cov(c) #计算协方差
print(d)

#（8）Basic Linear Algebra
#cross, dot, outer, linalg.svd, vdot

#










zeros_like:
 [0 0 0 0 0]
zeros_like:
 [1 1 1 1 1]
zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
all:
 False
8.0
