In [ ]:
#2.3 shape manipulation
#2018.04.01

In [11]:
#2.3.1 changing the shape of an array

import numpy as np
#改变数组的shape
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("shape:",a.shape)
print(a)
#以下三个方法可以改变array的shape，但是不改变原array
#返回一维数组
b = a.ravel() #flattened,返回一维数组
print("1darray:",b)
#返回一个修改的shape
b = a.reshape(6,2) #reshape()返回修改的array，参数乘积必须等于元素个数
print("6行2列：\n",b)
#转置
b = a.T #transposed，a的转置,即a[i,j]与a[j,i]互换位置
print("转置：\n",b)
print("a.T.shape: ",b.shape)
print("a.shape  : ",a.shape)
#array的元素顺序是C-style的，即右边索引变化最快(changes the fastest)
#因为在a[0,1]之后是a[0,1]
#reshape()返回一个修改的数组，resize()修改array本身,返回None
print("原array: \n",a)
b = a.resize(2,6)
print("b :\n",b)
print("a: \n",a)



shape: (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1darray: [ 1  2  3  4  5  6  7  8  9 10 11 12]
6行2列：
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
转置：
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
a.T.shape:  (4, 3)
a.shape  :  (3, 4)
原array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
b :
 None
a: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [54]:
#2.3.2 stacking together different arrays
import numpy as np
a = np.floor(10*np.random.random((2,2)))
print("a(1) : \n",a)
b = np.floor(10*np.random.random((2,2)))
print("b(1) : \n",b)
c = np.vstack((a,b)) #两个二维数组垂直组合
print("vstack(1):\n",c)
c = np.hstack((a,b)) #两个二维数组平行组合
print("hstack(1):\n",c)

from numpy import newaxis

c = np.column_stack((a,b)) #堆1darray作为列，成为2darray
print("column_stack(1):\n",c)#在二维时候和hstack()等同

a = np.array([4.,2.])
b = np.array([3.,8.])
#注意column_stack()与hstack()的区别，见下面例子：
c = np.column_stack((a,b))
print("column_stack(2): \n",c) 
c = np.hstack((a,b))
print("hstack(2): \n",c)
#一维数组，由1d行向量转为2d列向量
c = a[:,newaxis]
print("newaxis(1): \n",c)
#此处先将a,b转为列向量，在使用column_stack()将转换后的向量组合
c = np.column_stack((a[:,newaxis],b[:,newaxis]))
print("column_stack(3):\n",c)
#此处先将a,b转为列向量，在使用hstack()将转换后的向量组合
c = np.hstack((a[:,newaxis],b[:,newaxis]))
print("hstack(3):\n",c)

#row_stack()等同于vstack()

a = np.r_[1:4,0:3,4] #产生一维数组，允许使用冒号形式(:),连接到第一维
print("r_ : \n",a)
a = np.c_[1,2,3,4,5,6,6]#产生一维数组，允许使用冒号形式(:)，连接到第二维上
print("c_ : \n",a)
a = np.c_[np.array([[1,2,3]]),4,np.array([[7,8,9]])]#产生一维数组，允许使用冒号形式(:)，连接到第二维上
print("c_ : \n",a)
a = np.c_[[[1,2,3]],4,5,6,6]#产生一维数组，允许使用冒号形式(:)，连接到第二维上
print("c_ : \n",a)

print("--------------")
a = np.array([[4.],[2.]])
print("a ():\n",a)
print("shape: ",a.shape)
b = a[:,newaxis]
print("a(newaxis-r) \n:",b)
print("shape: ",b.shape)

print("--------------")
a = np.array([[4.],[2.]])
print("a ():\n",a)
print("shape: ",a.shape)
b = a[newaxis,:]
print("a(newaxis-l) \n:",b)
print("shape: ",b.shape)

print("--------------")
a = np.array([4.,2.])
print("a ():\n",a)
print("shape: ",a.shape)
b = a[:,newaxis]
print("a(newaxis-r) \n:",b)
print("shape: ",b.shape)

print("--------------")
a = np.array([4.,2.])
print("a ():\n",a)
print("shape: ",a.shape)
b = a[newaxis,:]
print("a(newaxis-l) \n:",b)
print("shape: ",b.shape)


a(1) : 
 [[4. 6.]
 [9. 4.]]
b(1) : 
 [[5. 8.]
 [6. 5.]]
vstack(1):
 [[4. 6.]
 [9. 4.]
 [5. 8.]
 [6. 5.]]
hstack(1):
 [[4. 6. 5. 8.]
 [9. 4. 6. 5.]]
column_stack(1):
 [[4. 6. 5. 8.]
 [9. 4. 6. 5.]]
column_stack(2): 
 [[4. 3.]
 [2. 8.]]
hstack(2): 
 [4. 2. 3. 8.]
newaxis(1): 
 [[4.]
 [2.]]
column_stack(3):
 [[4. 3.]
 [2. 8.]]
hstack(3):
 [[4. 3.]
 [2. 8.]]
r_ : 
 [1 2 3 0 1 2 4]
c_ : 
 [[1 2 3 4 5 6 6]]
c_ : 
 [[1 2 3 4 7 8 9]]
c_ : 
 [[1 2 3 4 5 6 6]]
--------------
a ():
 [[4.]
 [2.]]
shape:  (2, 1)
a(newaxis-r) 
: [[[4.]]

 [[2.]]]
shape:  (2, 1, 1)
--------------
a ():
 [[4.]
 [2.]]
shape:  (2, 1)
a(newaxis-l) 
: [[[4.]
  [2.]]]
shape:  (1, 2, 1)
--------------
a ():
 [4. 2.]
shape:  (2,)
a(newaxis-r) 
: [[4.]
 [2.]]
shape:  (2, 1)
--------------
a ():
 [4. 2.]
shape:  (2,)
a(newaxis-l) 
: [[4. 2.]]
shape:  (1, 2)


In [63]:
#2.3.3 splitting one array into several samaller ones
#讲一个数组分割成多个小数组
import numpy as np
a = np.floor(10*np.random.random((2,12)))
print(a)
b = np.hsplit(a,3) #沿水平轴切割成3个数组
print(b)

print("----------")
#切割成：第三列前面一个，第三列一个，第三列之后一个
b = np.hsplit(a,(3,4))
print(b)

print("----------")
#切割成：第三、四列前面一个，第三、四列一个，第三、四列之后一个
b = np.hsplit(a,(3,5))
print(b)








[[6. 5. 3. 3. 1. 4. 4. 4. 6. 7. 0. 2.]
 [6. 6. 9. 8. 0. 4. 4. 3. 8. 8. 6. 4.]]
[array([[6., 5., 3., 3.],
       [6., 6., 9., 8.]]), array([[1., 4., 4., 4.],
       [0., 4., 4., 3.]]), array([[6., 7., 0., 2.],
       [8., 8., 6., 4.]])]
----------
[array([[6., 5., 3.],
       [6., 6., 9.]]), array([[3.],
       [8.]]), array([[1., 4., 4., 4., 6., 7., 0., 2.],
       [0., 4., 4., 3., 8., 8., 6., 4.]])]
----------
[array([[6., 5., 3.],
       [6., 6., 9.]]), array([[3., 1.],
       [8., 0.]]), array([[4., 4., 4., 6., 7., 0., 2.],
       [4., 4., 3., 8., 8., 6., 4.]])]
