In [ ]:
#3.2 Array creation


In [ ]:
#3.2.1 Introduction
#有5种创建数组的方式，如下
#1. Conversion from other Python structures (e.g., lists, tuples)
#从其他Python结构转换
#2. Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)
#固有的numpy数组数组创建对象
#3. Reading arrays from disk, either from standard or custom formats
#从磁盘读取数组，无论是标准的还是自定义格式
#4. Creating arrays from raw bytes through the use of strings or buffers
#通过使用字符串或缓冲器从原始字节创建数组
#5. Use of special library functions (e.g., random)
#使用特殊的库函数

In [1]:
#3.2.2 Converting Python array_like Objects to NumPy Arrays
import numpy as np 
x = np.array([2,3,1,0])
x = np.array([2, 3, 1, 0])
# note mix of tuple and lists,and types
x = np.array([[1,2.0],[0,0],(1+1j,3.)]) 
x = np.array([[ 1.+0.j, 2.+0.j], [ 0.+0.j, 0.+0.j], [ 1.+1.j, 3.+0.j]])

In [9]:
#3.2.3 Intrinsic NumPy Array Creation
import numpy as np 
a = np.zeros((2, 3))
print("zeros :\n",a)
print("----------------")
a = np.arange(10)
print("arange:\n",a)
print("----------------")
a = np.arange(2, 10, dtype=float)
print("arange(float):\n",a)
print("----------------")
a = np.arange(2, 3, 0.1)
print("arange(2,3,0.1):\n",a)

print("----------------")
a = np.linspace(1., 4., 6)
print("linspace(1,4,6):\n",a)
print("----------------")
a = np.indices((3,3))
print("indices(3,3):\n",a)
print("indices shape: ",a.shape)


zeros :
 [[0. 0. 0.]
 [0. 0. 0.]]
----------------
arange:
 [0 1 2 3 4 5 6 7 8 9]
----------------
arange(float):
 [2. 3. 4. 5. 6. 7. 8. 9.]
----------------
arange(2,3,0.1):
 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
----------------
linspace(1,4,6):
 [1.  1.6 2.2 2.8 3.4 4. ]
----------------
indices(3,3):
 [[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]
indices shape:  (2, 3, 3)


In [10]:
#3.2.4 Reading Arrays From Disk
#最常用于大数组的创建
#（1）Standard Binary Formats
#HDF5: h5py
#FITS: Astropy

#（2）Common ASCII Formats
#如CSV格式的文件

#（3）Custom Binary Formats

#（4）Use of Special Libraries

