In [9]:
#Indexing
import numpy as np
a = np.arange(10)
print("array a:\n",a)
print(a[2])
print(a[-2])#负数也可以作为索引，但是从-1开始，-1表示一维数组的最后一个元素，往前是-2，以此类推

a.shape = (2,5)#shape可以改变数组的形状
print("array a:\n",a)
print(a[1,3])#访问二维数组中某个元素的第一种方式

print("a[0]=:\n",a[0])#对于二维数组，a[0]表示其中的一行

print("a[0][2]=:\n",a[0][2])#访问二维数组中某个元素的第二总方式



array a:
 [0 1 2 3 4 5 6 7 8 9]
2
8
array a:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
8
a[0]=:
 [0 1 2 3 4]
a[0][2]=:
 2
