In [ ]:
#2.7 linear algebra


In [7]:
#2.7.1 Simple Array Operations
import numpy as np
a = np.array([[1.0,2.0],[3.0,4.0]])
print("a: \n",a)
b = a.transpose() #转置
print("transpose b:\n",b)
c = np.linalg.inv(a) #求矩阵的逆
print("linalg.inv c :\n",c)

y = np.array([[5.], [7.]])
c = np.linalg.solve(a, y) #解线性方程组ax=y，返回解x
print("linear solve c:\n",c)

c = np.trace(a) #矩阵的迹,主对角线上元素的和
print("trace c :",c)

j = np.array([[0.0, -1.0], [1.0, 0.0]])
c = np.linalg.eig(j) #计算方阵的特征值和右特征值
print("linalg.eig c:\n",c)


a: 
 [[1. 2.]
 [3. 4.]]
transpose b:
 [[1. 3.]
 [2. 4.]]
linalg.inv c :
 [[-2.   1. ]
 [ 1.5 -0.5]]
linear solve c:
 [[-3.]
 [ 4.]]
trace c : 5.0


linalg.eig c:
 (array([0.+1.j, 0.-1.j]), array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j]]))


In [ ]:
#2.8 Tricks and Tips

In [9]:
#2.8.1 “Automatic” Reshaping
import numpy as np
a = np.arange(30)
print("a:\n",a)
a.shape = 2,-1,3 # -1 means "whatever is needed"
print("shape :\n",a.shape)
print("a:\n",a)


a:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
shape :
 (2, 5, 3)
a:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [10]:
#2.8.2 Vector Stacking
import numpy as np
x = np.arange(0,10,2) # x=([0,2,4,6,8])
print("x:\n",x)
y = np.arange(5) # y=([0,1,2,3,4])
print("y:\n",y)
m = np.vstack([x,y]) # m=([[0,2,4,6,8], [0,1,2,3,4]])
print("vstack:\n",m)
xy = np.hstack([x,y]) # xy =([0,2,4,6,8,0,1,2,3,4])
print("hstack:\n",xy)

x:
 [0 2 4 6 8]
y:
 [0 1 2 3 4]
vstack:
 [[0 2 4 6 8]
 [0 1 2 3 4]]
hstack:
 [0 2 4 6 8 0 1 2 3 4]


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
# Build a vector of 10000 normal deviates with variance 0.5^2 and mean 2
mu, sigma = 2, 0.5
v = np.random.normal(mu,sigma,10000)
# Plot a normalized histogram with 50 bins
plt.hist(v, bins=50, density=1) # matplotlib version (plot)
plt.show()
print("=================================================")
# Compute the histogram with numpy and then plot it
(n, bins) = np.histogram(v, bins=50, normed=True) # NumPy version (no plot)
plt.plot(.5*(bins[1:]+bins[:-1]), n)
plt.show()

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>